version: '3.8'

services:
  goservice:
    restart: always
    build: ./
    container_name: "web"

    ports:
      - "9090"
    environment:
      - "MONGODB_URI=mongodb://db:27017"
    depends_on:
      - db
    networks:
      - fullstack
  goservice1:
    restart: always
    build: /home/denys/go/src/JokesApp_SecondVersion_copy
    container_name: "web111"

    ports:
      - "8080"
    environment:
      - "MONGODB_URI=mongodb://db:27017"
    depends_on:
      - db
    networks:
      - fullstack

  db:
    restart: always
    image: mongo:5.0
    container_name: "database"
    volumes:
      - ~/data7/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - fullstack
  nginx:
    build: "./nginx"

    container_name: "nginx"

    depends_on:
      - "goservice"
    ports:
      - "80:80"
      #- "443:443"
    restart: unless-stopped
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
