version: '3.8'

services:
  web:
    restart: always
    image: 1461721/go-app:1.1
    container_name: "web"

    ports:
      - "9090:9090"
    environment:
      - "MONGODB_URI=mongodb://db:27017"
    depends_on:
      - db
    networks:
      - fullstack

  db:
    restart: always
    image: mongo:4.2
    container_name: "database"
    volumes:
      - database_mongo:/home/data/db
    ports:
      - "27017:27017"
    networks:
      - fullstack

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
volumes:
  database_mongo:

    null
networks:
  fullstack:
    driver: bridge
