version: '3.8'

services:
  web:
    restart: always
    image: goapp:1.4
    container_name: "web"

    ports:
      - "9090:9090"
    environment:
      - "MONGODB_URI=mongodb://db:27017"
    depends_on:
      - db
    networks:
      - fullstack

  db:
    restart: always
    image: mongo:5.0
    container_name: "database"
    volumes:
      - ~/data7/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
